import {
  Layout,
  Building,
  FileText,
  Calculator,
  Settings,
  Image,
  User,
  Hash,
  Calendar,
  List,
  Percent,
  Tag,
  PenTool,
  Folder,
  StickyNote,
  Shield,
  QrCode,
  CreditCard,
  Flag,
  GitBranch,
  Lock,
  Clock,
  Wrench,
  Package,
  MinusCircle,
  DollarSign,
} from "lucide-react";

export const iconComponents: Record<string, React.ComponentType<{ className?: string }>> = {
  layout: Layout,
  building: Building,
  "file-text": FileText,
  calculator: Calculator,
  settings: Settings,
  image: Image,
  user: User,
  hash: Hash,
  calendar: Calendar,
  list: List,
  percent: Percent,
  tag: Tag,
  "pen-tool": PenTool,
  folder: Folder,
  "sticky-note": StickyNote,
  shield: Shield,
  "qr-code": QrCode,
  "credit-card": CreditCard,
  flag: Flag,
  "git-branch": GitBranch,
  lock: Lock,
  clock: Clock,
  wrench: Wrench,
  package: Package,
  "minus-circle": MinusCircle,
  "dollar-sign": DollarSign,
};

export function getIconComponent(name: string): React.ComponentType<{ className?: string }> {
  return iconComponents[name] || Settings;
}

export function getIconComponentForType(type: string): React.ComponentType<{ className?: string }> {
  const typeToIcon: Record<string, string> = {
    text: "file-text",
    image: "image",
    customerInfo: "user",
    invoiceNumber: "hash",
    date: "calendar",
    lineItems: "list",
    subtotal: "calculator",
    tax: "percent",
    discount: "tag",
    paymentTerms: "file-text",
    signature: "pen-tool",
    customField: "settings",
    businessInfo: "building",
    projectInfo: "folder",
    notes: "sticky-note",
    terms: "shield",
    qrCode: "qr-code",
    paymentButton: "credit-card",
    milestoneInfo: "flag",
    changeOrders: "git-branch",
    scheduleOfValues: "layout",
    retainage: "lock",
    previousPayments: "credit-card",
    laborTable: "clock",
    materialsTable: "package",
    equipmentTable: "wrench",
    discounts: "minus-circle",
    taxes: "percent",
    paymentSummary: "dollar-sign",
    section: "layout",
    row: "layout",
    column: "layout",
  };

  return getIconComponent(typeToIcon[type] || "settings");
}