ALTER TYPE "InvoiceType" ADD VALUE 'FIXED_PRICE';
ALTER TYPE "InvoiceType" ADD VALUE 'TIME_AND_MATERIALS';
ALTER TYPE "InvoiceType" ADD VALUE 'MILESTONE';
ALTER TYPE "InvoiceType" ADD VALUE 'CHANGE_ORDER';
ALTER TYPE "InvoiceType" ADD VALUE 'DEPOSIT';
ALTER TYPE "InvoiceType" ADD VALUE 'RETAINAGE';
ALTER TYPE "InvoiceType" ADD VALUE 'FINAL';
ALTER TYPE "InvoiceType" ADD VALUE 'CUSTOM';
